// import './example/basic-type'
// import './example/symbol'
// import './example/interface'
// import './example/function'
// import './example/generics'
// import './example/es6-class-1.js'
// import './example/es6-class-2.js'
// import './example/class'
// import './example/inference-compatibility'
import './example/advanced-type-1'
